[package]
name = "podway-config"
version = "0.2.5"
edition = "2024"
license = "MIT"
publish = false
autotests = false

[dependencies]
podway-core = { path = "../podway-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
serde_yaml.workspace = true
yaml-rust2.workspace = true

[[test]]
name = "int_suite"
path = "tests/int_suite.rs"
