[package]
name = "podway-presets"
version = "0.2.1"
edition = "2024"
license = "MIT"
publish = false
autotests = false

[dependencies]
podway-core = { path = "../podway-core" }
podway-config = { path = "../podway-config" }
serde.workspace = true

[[test]]
name = "int_suite"
path = "tests/int_suite.rs"
